name: Products
type: object
key: sku
data:
  min: 1000
properties:
  name:
    description: The product name
    data:
      fake: '{{commerce.productName}}'
  sku:
    description: The product sku
    data:
      fake: '{{random.alphaNumeric}}{{random.alphaNumeric}}{{random.alphaNumeric}}{{random.alphaNumeric}}{{random.alphaNumeric}}{{random.alphaNumeric}}'
  price:
    description: The product price
    data:
      fake: '{{finance.amount}}'
